export const FETCH_RESTAURENTS = 'FETCH_RESTAURENTS';
export const SIGNUP="SIGNUP";
export const SIGNIN ="SIGNIN";
export const FETCH_RESTAURENT_BYID='FETCH_RESTAURENT_BYID';
export const FETCH_MENU_BYID ='FETCH_MENU_BYID';

